# Config options
markdown: kramdown
sass:
  style: :compressed
  sass_dir: _sass
permalink: /posts/:title/
gems:
  - jekyll-redirect-from
  - jekyll-feed
timezone: America/New_York

# Site-level data
name: Viktor Lysko
keywords:
  - viktor lysko
  - software engineer
  - developer
  - cryptography
  - C++/ C/Python
description: "I make things."
excerpt_separator: <!--more-->
